# Generated by Django 4.1.7 on 2023-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="temperature",
            name="caphumidity",
            field=models.CharField(default=99, max_length=10),
            preserve_default=False,
        ),
    ]
