# Generated by Django 4.1.7 on 2023-06-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0002_temperature_caphumidity"),
    ]

    operations = [
        migrations.AddField(
            model_name="temperature",
            name="capillumination",
            field=models.CharField(default=99, max_length=10),
        ),
        migrations.AddField(
            model_name="temperature",
            name="capsoilmoisture",
            field=models.CharField(default=99, max_length=10),
        ),
    ]
